//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 4/13/2009 11:24:27 AM
namespace GPUApp.Models
{
    
    
    public partial class GPUDBEntities : global::System.Data.Objects.ObjectContext
    {
       
        public GPUDBEntities() : 
                base("name=GPUDBEntities", "GPUDBEntities")
        {
            this.OnContextCreated();
        }

        public GPUDBEntities(string connectionString) : 
                base(connectionString, "GPUDBEntities")
        {
            this.OnContextCreated();
        }
        

        public GPUDBEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "GPUDBEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        
        public global::System.Data.Objects.ObjectQuery<GPU> GPUSet
        {
            get
            {
                if ((this._GPUSet == null))
                {
                    this._GPUSet = base.CreateQuery<GPU>("[GPUSet]");
                }
                return this._GPUSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<GPU> _GPUSet;
       

        public void AddToMovieSet(GPU gpu)
        {
            base.AddObject("GPUSet", GPU);
        }
    }
    

    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="GPUApp.Models", Name="GPU")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class GPU: global::System.Data.Objects.DataClasses.EntityObject
    {
       

        public static GPU CreateGPU(int id, string Model, string director, global::System.DateTime dateReleased)
        {
            GPU gpu = new GPU();
            gpu.Id = id;
            gpu.Title = Model;
            gpu.DateReleased = dateReleased;
            return GPU;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
       

        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Model;
            }
            set
            {
                this.OnModelChanging(value);
                this.ReportPropertyChanging("Model");
                this._Model = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Model");
                this.OnModelChanged();
            }
        }
        private string _Model;
        partial void OnModelChanging(string value);
        partial void OnModelChanged();
        
      
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime DateReleased
        {
            get
            {
                return this._DateReleased;
            }
            set
            {
                this.OnDateReleasedChanging(value);
                this.ReportPropertyChanging("DateReleased");
                this._DateReleased = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DateReleased");
                this.OnDateReleasedChanged();
            }
        }
        private global::System.DateTime _DateReleased;
        partial void OnDateReleasedChanging(global::System.DateTime value);
        partial void OnDateReleasedChanged();
    }
}
